In [4]:
import pandas as pd

In [ ]:
anime = pd.read_csv('anime.csv')

In [10]:
print(anime)

       anime_id                                               name  \
0         32281                                     Kimi no Na wa.
1          5114                   Fullmetal Alchemist: Brotherhood
2         28977                                           Gintama°
3          9253                                        Steins;Gate
4          9969                                      Gintama&#039;
...         ...                                                ...
12289      9316       Toushindai My Lover: Minami tai Mecha-Minami
12290      5543                                        Under World
12291      5621                     Violence Gekiga David no Hoshi
12292      6133  Violence Gekiga Shin David no Hoshi: Inma Dens...
12293     26081                   Yasuji no Pornorama: Yacchimae!!

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1
1      Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64
2      Action, Comedy, Historical, Parody, Samurai, S...     TV       51
3                                       Sci-Fi, Thriller     TV       24
4      Action, Comedy, Historical, Parody, Samurai, S...     TV       51
...                                                  ...    ...      ...
12289                                             Hentai    OVA        1
12290                                             Hentai    OVA        1
12291                                             Hentai    OVA        4
12292                                             Hentai    OVA        1
12293                                             Hentai  Movie        1

       rating  members
0        9.37   200630
1        9.26   793665
2        9.25   114262
3        9.17   673572
4        9.16   151266
...       ...      ...
12289    4.15      211
12290    4.28      183
12291    4.88      219
12292    4.98      175
12293    5.46      142

[12294 rows x 7 columns]

Feature Selection Part

In [15]:
anime.columns

Index(['anime_id', 'name', 'genre', 'rating'], dtype='object')

In [11]:
anime = anime[['anime_id', 'name', 'genre', 'rating']]

In [12]:
anime

,anime_id,name,genre,rating
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",9.37
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",9.26
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",9.25
3,9253,Steins;Gate,"Sci-Fi, Thriller",9.17
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",9.16
...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,4.15
12290,5543,Under World,Hentai,4.28
12291,5621,Violence Gekiga David no Hoshi,Hentai,4.88
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,4.98
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,5.46

In [27]:
anime['tags'] = anime['genre']

In [28]:
anime = anime.drop(columns=['tags'])

In [29]:
from sklearn.feature_extraction.text import CountVectorizer

In [30]:
cv = CountVectorizer(max_features=12294, stop_words = 'english')

In [31]:
cv

CountVectorizer(max_features=12294, stop_words='english')

In [32]:
vector = cv.fit_transform(anime['genre'].values.astype('U')).toarray()

In [33]:
vector.shape

(12294, 47)

In [34]:
from sklearn.metrics.pairwise import cosine_similarity

In [35]:
similarity = cosine_similarity(vector)

In [36]:
similarity

array([[1.        , 0.18898224, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.18898224, 1.        , 0.26726124, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.26726124, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        1.        ]])

In [39]:
anime[anime['name']=="Fullmetal Alchemist: Brotherhood"].index[0]

1

In [58]:
distance = sorted(list(enumerate(similarity[1])), reverse = True, key = lambda vector:vector[1])
for i in distance[0:10]:
    print (anime.iloc[i[0]]['name'])

Fullmetal Alchemist: Brotherhood
Fullmetal Alchemist
Fullmetal Alchemist: The Sacred Star of Milos
Fullmetal Alchemist: Brotherhood Specials
Kkomaeosa Ttori
Magi: The Kingdom of Magic
Magi: The Labyrinth of Magic
Magi: Sinbad no Bouken (TV)
Magi: Sinbad no Bouken
Densetsu no Yuusha no Densetsu

In [65]:
def recommend(anime_title):
    index = anime[anime['name']==anime_title].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse = True, key = lambda vector:vector[1])
    for i in distance[0:10]:
        print (anime.iloc[i[0]]['name'])

In [66]:
recommend("Magi: The Kingdom of Magic")

Magi: The Kingdom of Magic
Magi: The Labyrinth of Magic
Magi: Sinbad no Bouken (TV)
Magi: Sinbad no Bouken
Densetsu no Yuusha no Densetsu
Log Horizon Recap
Dragon Quest: Dai no Daibouken Tachiagare!! Aban no Shito
Dragon Quest: Dai no Daibouken Buchiyabure!! Shinsei 6 Daishougun
Densetsu no Yuusha no Densetsu: Iris Report
Chain Chronicle: Short Animation

In [67]:
import pickle

In [68]:
pickle.dump(anime, open('anime_list.plk', 'wb'))

In [71]:
pickle.dump(similarity, open('similarity.plk', 'wb'))

In [72]:
pickle.load(open('anime_list.plk', 'rb'))

,anime_id,name,genre,rating
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",9.37
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",9.26
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",9.25
3,9253,Steins;Gate,"Sci-Fi, Thriller",9.17
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",9.16
...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,4.15
12290,5543,Under World,Hentai,4.28
12291,5621,Violence Gekiga David no Hoshi,Hentai,4.88
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,4.98
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,5.46